name: Pull request checks 

on:
  push:
    branches: [ main ]
    paths:
        - 'academiesContracts/**'
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths:
        - 'academiesContracts/**'

defaults:
    run:
        working-directory: academiesContracts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v1
        - name: Build
          run: dotnet build -c Release
        - name: Test
          run: dotnet test -c Release --no-build